#!/usr/bin/env python3
"""Decode animation GIFs (assets/faces/generated/animations/*.gif) into 128x32
1-bit PROGMEM frame arrays for mcu/robot_body_faces/pet_faces_anim.h.

Uses the exact same row-packed, MSB-first bit layout as
assets/faces/generate_faces.py:pack_bitmap (the format already baked into
mcu/robot_body_faces/pet_faces.h), so the new animation frames and the
existing static faces are byte-compatible and drawBitmap()-ready.

Each animation GIF was rendered at 4x scale with NEAREST resampling (see
generate_animations.py:write_gif), so every 4x4 block in a decoded frame is a
solid color with no blending — point-sampling one pixel per block recovers
the original 128x32 grid exactly, no interpolation involved.

Run: /Users/rishwajeetsingh/Documents/machine_house/.venv/bin/python gif_to_frames.py
"""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent               # assets/faces
STATIC_DIR = ROOT / "generated"
ANIM_DIR = STATIC_DIR / "animations"
OUT_HEADER = ROOT.parent.parent / "mcu" / "robot_body_faces" / "pet_faces_anim.h"
STATIC_HEADER = ROOT.parent.parent / "mcu" / "robot_body_faces" / "pet_faces.h"

WIDTH, HEIGHT = 128, 32
SCALE = 4      # animation GIFs are rendered at 4x for visibility
THRESHOLD = 64  # grayscale cut: background ~#071018 (luma ~16) vs any drawn color (luma 140-190)

# Only convert animations that map onto an existing static agent-face state
# (agentFaceFromName in robot_body_faces.ino). idle_blink/working_scan/
# listening_pulse/speaking_mouth/meme_six_seven have no matching bitmap slot
# wired today, so they're left unconverted rather than forced in.
ANIMATIONS = [
    "claude_permission",
    "claude_tool_running",
    "claude_done",
    "claude_needs_input",
]


def pack_bitmap(image):
    """Pack a 128x32 mode-'1' image rows MSB-first, matching generate_faces.py."""
    data = []
    for y in range(HEIGHT):
        for x0 in range(0, WIDTH, 8):
            byte = 0
            for bit in range(8):
                if image.getpixel((x0 + bit, y)):
                    byte |= 1 << (7 - bit)
            data.append(byte)
    return data


def decode_gif_frames(path):
    """Return a list of 128x32 mode-'1' PIL images, one per GIF frame."""
    im = Image.open(path)
    frames = []
    for i in range(im.n_frames):
        im.seek(i)
        frame = im.convert("RGB")
        small = frame.resize((WIDTH, HEIGHT), Image.Resampling.NEAREST)
        bw = small.convert("L").point(lambda p: 255 if p > THRESHOLD else 0).convert("1")
        frames.append(bw)
    return frames


def parse_existing_array(header_text, array_name):
    marker = f"{array_name}[] PROGMEM = {{"
    start = header_text.index(marker) + len(marker)
    end = header_text.index("};", start)
    block = header_text[start:end]
    return [int(tok, 16) for tok in block.replace("\n", " ").split(",") if "0x" in tok]


def verify_against_static():
    """Byte-match proof: run pack_bitmap() on the existing idle.png and diff
    against the PET_FACE_IDLE array already baked into pet_faces.h."""
    idle_png = Image.open(STATIC_DIR / "idle.png").convert("1")
    ours = pack_bitmap(idle_png)
    existing = parse_existing_array(STATIC_HEADER.read_text(), "PET_FACE_IDLE")
    match = ours == existing
    print(f"[verify] idle.png -> pack_bitmap() vs PET_FACE_IDLE: "
          f"{'MATCH' if match else 'MISMATCH'} ({len(ours)} bytes, expected {len(existing)})")
    return match


def emit_header(all_frames):
    lines = [
        "// Generated by assets/faces/gif_to_frames.py. Do not edit.",
        "// Row-packed MSB-first 128x32 frames, same layout as pet_faces.h",
        "// (verified byte-identical against PET_FACE_IDLE — see script output).",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    for name, frames in all_frames.items():
        upper = name.upper()
        for idx, frame in enumerate(frames):
            data = pack_bitmap(frame)
            lines.append(f"const uint8_t PET_ANIM_{upper}_F{idx}[] PROGMEM = {{")
            for start in range(0, len(data), 16):
                chunk = ", ".join(f"0x{v:02X}" for v in data[start:start + 16])
                lines.append(f"  {chunk},")
            lines.extend(["};", ""])
        # Plain (non-PROGMEM) pointer index — only 4 pointers, negligible RAM,
        # avoids any pgm_read_ptr concerns on the Zephyr/UNO Q target.
        lines.append(f"const uint8_t* PET_ANIM_{upper}_FRAMES[] = {{")
        for idx in range(len(frames)):
            lines.append(f"  PET_ANIM_{upper}_F{idx},")
        lines.append("};")
        lines.append(f"constexpr uint8_t PET_ANIM_{upper}_COUNT = {len(frames)};")
        lines.append("")
    OUT_HEADER.write_text("\n".join(lines))


def main():
    if not verify_against_static():
        raise SystemExit("byte-match verification failed against pet_faces.h — aborting")

    all_frames = {}
    for name in ANIMATIONS:
        gif_path = ANIM_DIR / f"{name}.gif"
        frames = decode_gif_frames(gif_path)
        for f in frames:
            assert f.size == (WIDTH, HEIGHT), f"{name}: unexpected frame size {f.size}"
        all_frames[name] = frames
        print(f"[convert] {name}: {len(frames)} frames from {gif_path.name}")

    emit_header(all_frames)
    total_bytes = sum(len(frames) * (WIDTH * HEIGHT // 8) for frames in all_frames.values())
    print(f"Wrote {OUT_HEADER} ({total_bytes} bytes of frame data)")


if __name__ == "__main__":
    main()
